version: 2
defaults: &defaults
    machine:
      image: circleci/classic:edge
    steps:
      - run:
          name: Check docker is running
          command: docker info
      - run:
          name: Pull Community Hass.io Add-ons build environment
          command: docker pull hassioaddons/build-env:latest
      - run:
          name: Log in to Docker Hub
          command: |
            if [[ "${CIRCLE_BRANCH}" = "master" || ! -z "${CIRCLE_TAG:-}" ]];
            then
              docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
            fi
      - checkout
      - deploy:
          name: Build and (maybe) deploy
          command: |
              if [[ "${CIRCLE_BRANCH}" = "master" || ! -z "${CIRCLE_TAG:-}" ]];
              then
                docker run \
                  --privileged \
                  -v ~/.docker:/root/.docker \
                  -v "$PWD":/docker \
                  hassioaddons/build-env:latest \
                  --image "hassioaddons/ide-{arch}" \
                  --git \
                  --target ide \
                  --${ARCH} \
                  --push
              else
                docker run \
                  --privileged \
                  -v "$PWD":/docker \
                  hassioaddons/build-env:latest \
                  --image "hassioaddons/ide-{arch}" \
                  --git \
                  --target ide \
                  --${ARCH}
              fi
      - deploy:
          name: Send notification to Microbadger
          command: |
              if [[ "${CIRCLE_BRANCH}" = "master" || ! -z "${CIRCLE_TAG:-}" ]];
              then
                curl -X POST https://hooks.microbadger.com/images/${MICROBADGER_WEBHOOK}
              fi

jobs:
  aarch64:
    <<: *defaults
    environment:
      ARCH: aarch64
      MICROBADGER_WEBHOOK: hassioaddons/ide-aarch64/9jaubXbtoSWgIVBfX87rwoVMaWQ=
  amd64:
    <<: *defaults
    environment:
      ARCH: amd64
      MICROBADGER_WEBHOOK: hassioaddons/ide-amd64/ZxRJsC3x8YJgZtoS5Ya-q32M1jM=
  armhf:
    <<: *defaults
    environment:
      ARCH: armhf
      MICROBADGER_WEBHOOK: hassioaddons/ide-armhf/-wZnzAXd5GFHp4oOBEJ1scAgo1c=
  i386:
    <<: *defaults
    environment:
      ARCH: i386
      MICROBADGER_WEBHOOK: hassioaddons/ide-i386/P8n5QhBhI3F4fyAn_10ALb0srGw=

workflows:
  version: 2
  build_and_maybe_deploy:
    jobs:
      - aarch64:
          filters:
            tags:
              only: /.*/
      - amd64:
          filters:
            tags:
              only: /.*/
      - armhf:
          filters:
            tags:
              only: /.*/
      - i386:
          filters:
            tags:
              only: /.*/
